### ISSUE TITLE
Set up branch protection

### ISSUE THREAD

**Issue by mciach** [mdrago98/BiogeMtBootcampTask#1]
Set up protection rules for the main branch: require a pull request before merging; require 2 approvals before merging

**Comment by mdrago98** [comment]
Added a branch protection rule on the main branch. Collaborators will need an approval of 2 collaborators on their PR before merging to the main

**Comment by edward-blake** [comment]
For task 1 and 2, please have all the outputs have the following format:
Name // Seq number // A% // T% // G% // C%

and

Name // Seq number // Length
